[profile.default]
  solc = "0.8.24"
  src = "src"
  out = "out"
  libs = ["lib"]
  via-ir = true
  optimizer = true
  optimizer_runs = 200
  evm_version = "paris"
  fs_permissions = [{ access = "read-write", path = "./deployments/"}]
  build_info = true
  extra_output = ["storageLayout"]

[profile.lite.optimizer_details.yulDetails]
  optimizerSteps = ''

[rpc_endpoints]
  sepolia = "${SEPOLIA_RPC_URL}"

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true