[profile.default]
  solc = "0.8.26"
  evm_version="cancun"
  src = "src"
  out = "out"
  libs = ["lib"]
  via-ir = true
  optimizer = true
  optimizer_runs = 1000
  fs_permissions = [{ access = "read-write", path = "./deployments/"}]

[rpc_endpoints]
  sepolia = "${SEPOLIA_RPC_URL}"

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true